FROM openjdk:8
LABEL maintainer="joaquin@nurelm.com"

COPY . /aware-micro
WORKDIR /aware-micro

ARG DB_ENGINE
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PWD
ARG DB_ROOT_PWD
ARG DB_PORT
ARG SERVER_HOST
ARG SERVER_PORT
ARG WEBSOCKET_PORT

ENV DB_ENGINE $DB_ENGINE
ENV DB_HOST $DB_HOST
ENV DB_NAME $DB_NAME
ENV DB_USER $DB_USER
ENV DB_PWD $DB_PWD
ENV DB_ROOT_PWD $DB_ROOT_PWD
ENV DB_PORT $DB_PORT
ENV SERVER_HOST $SERVER_HOST
ENV SERVER_PORT $SERVER_PORT
ENV STUDY_START 1571756837937
ENV WEBSOCKET_PORT $WEBSOCKET_PORT

ENTRYPOINT ["/aware-micro/entrypoint.sh"]
CMD ["clean", "build", "run"]
